AWSTemplateFormatVersion: 2010-09-09
Description: creates an Ubuntu EC2 instance with it's corresponsing Security Group

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref UbuntuInstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-0279c3b3186e54acd' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t3.micro

  UbuntuInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0